HALF_PI = Math.PI / 2;
TWO_PI = Math.PI * 2;

WORLD_RADIUS = 300.0;
WORLD_RESOLUTION = 32;

WATER_WAVE_PERIOD = 10000.0;

ENTITY_SPACE_WIDTH = 360.0;
ENTITY_SPACE_HEIGHT = 180.0;

DUCK_VELOCITY = 250.0;
DUCK_ROTATION_VELOCITY = 3.5;

DUCKLING_PICKUP_DISTANCE = 50.0;
DUCKLING_FOLLOW_DISTANCE = 150.0;
DUCKLING_COLLISION_DISTANCE = DUCKLING_FOLLOW_DISTANCE * 0.75;
DUCKLING_VELOCITY_FACTOR = 1.05;
DUCKLING_IN_PLACE_DISTANCE = DUCKLING_COLLISION_DISTANCE;

HERON_SNACK_DISTANCE = 100;

BREADCRUMB_DISTANCE = DUCKLING_FOLLOW_DISTANCE;
BREADCRUMB_REACHED_DISTANCE = BREADCRUMB_DISTANCE * 0.5;
BREADCRUMB_ALLOWED_DISTANCE = DUCKLING_FOLLOW_DISTANCE * 2.5;

WORLD_DETAIL_TREE_COUNT = 12;
WORLD_DETAIL_LOG_COUNT = 8;

AUDIO_VOLUME = 0.2;

